version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
  slack: circleci/slack@3.2.0
jobs:
  build_jar:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init
      - barkendeploy/gradle-cache-restore
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build jar file
          command: ./gradlew shadowJar -x test
      - barkendeploy/gradle-cache-persist
      - barkendeploy/docker-build
      - barkendeploy/docker-login
      - barkendeploy/docker-push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_jar:
          context: barkendeploy
          filters:
            branches:
              only: master
      - barkendeploy/deployment:
          deployments:
            - barkendeploy/deploy-create:
                cluster: dev-fss
          #  - barkendeploy/deploy-create:
          #      cluster: prod-fss
          context: barkendeploy
          requires:
            - build_jar
  build_branch:
    jobs:
      - build_jar:
          context: barkendeploy
          filters:
            branches:
              ignore: master
      - slack/approval-notification:
          context: barkendeploy
          name: deploy_branch
          mentions: here
          message: Repoet ${CIRCLE_PROJECT_REPONAME} trenger godkjennelse for Ã¥ deploye branchen ${CIRCLE_BRANCH} til dev-fss
          requires:
            - build_jar
      - await_approval_branch:
          type: approval
          requires:
            - build_jar
      - barkendeploy/deployment:
          context: barkendeploy
          deployments:
            - barkendeploy/deploy-create:
                cluster: dev-fss
          requires:
            - await_approval_branch
